[package]
name = "vs_ide"
version = "0.1.3"
edition = "2021"

[lib]
name = "vs_ide"
path = "src/lib.rs"

[dependencies]
tauri = { version = "2.11.5", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
yoke-derive = "=0.8.2"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
